vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        livres:
           uri_prefix: /images/livres
           upload_destination: '%kernel.project_dir%/public/images/livres'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #    remplacer tous les products par le nom de class où il y a des images: C'est ce qu'on a fait au-dessus
        auteurs:
           uri_prefix: /images/auteurs
           upload_destination: '%kernel.project_dir%/public/images/auteurs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
